Download and Import Packages

In [49]:
%pip install pandas
%pip install numpy
%pip install xlsxwriter
import pandas as pd
import numpy as np 
import xlsxwriter

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\Edumo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Edumo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Edumo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Edumo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Edumo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in C:\Users\Edumo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (2.5.1)
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xlsxwriter in C:\Users\Edumo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.2.9)
Note: you may need to restart the kernel to use updated packages.

Import & Verify Data

In [32]:
## Load raw dataset
df = pd.read_csv(r"C:\Users\Edumo\Downloads\Messy_HR_Dataset_Detailed.csv")

In [33]:
## Verify dataset loaded successfully
df.head()

,Unnamed: 0,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Satisfaction Score,Work-Life Balance Score,Training Date,Training Program Name,Training Type,Training Outcome,Location,Trainer,Training Duration(Days),Training Cost
0,0,Uriah,Bridges,20-Sep-19,NaN,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,...,2,3,15-Jul-23,Leadership Development,Internal,Failed,South Marisa,Taylor Rodriguez,2,606.11
1,1,Paula,Small,11-Feb-23,NaN,Production Technician I,Renee Mccormick,paula.small@bilearner.com,EW,Active,...,1,5,12-Sep-22,Customer Service,External,Incomplete,Tammieville,Kelly Patterson DDS,4,673.02
2,2,Edward,Buck,10-Dec-18,NaN,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,...,2,1,13-Aug-22,Leadership Development,External,Failed,East Roberthaven,Taylor Thomas,2,413.28
3,3,Michael,Riordan,21-Jun-21,NaN,Area Sales Manager,Rebekah Wright,michael.riordan@bilearner.com,CCDR,Active,...,5,4,15-Dec-22,Project Management,External,Completed,Garzatown,Holly Elliott,3,663.78
4,4,Jasmine,Onque,29-Jun-19,NaN,Area Sales Manager,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,...,5,3,13-Jul-23,Technical Skills,External,Failed,Lake Meganville,Donald Martinez,5,399.03

In [34]:
## Look at data types and null values 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3150 entries, 0 to 3149
Data columns (total 39 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  3150 non-null   int64
 1   FirstName                   3150 non-null   str
 2   LastName                    3150 non-null   str
 3   StartDate                   3150 non-null   str
 4   ExitDate                    1606 non-null   str
 5   Title                       3150 non-null   str
 6   Supervisor                  3150 non-null   str
 7   ADEmail                     3150 non-null   str
 8   BusinessUnit                3150 non-null   str
 9   EmployeeStatus              3150 non-null   str
 10  EmployeeType                3150 non-null   str
 11  PayZone                     3150 non-null   str
 12  EmployeeClassificationType  3150 non-null   str
 13  TerminationType             3150 non-null   str
 14  TerminationDescription      1606 non-null   str
 15  DepartmentType              3150 non-null   str
 16  Division                    3150 non-null   str
 17  DOB                         3150 non-null   str
 18  State                       3150 non-null   str
 19  JobFunctionDescription      3150 non-null   str
 20  GenderCode                  3150 non-null   str
 21  LocationCode                3150 non-null   int64
 22  RaceDesc                    3150 non-null   str
 23  MaritalDesc                 3150 non-null   str
 24  Performance Score           3150 non-null   str
 25  Current Employee Rating     3150 non-null   int64
 26  Employee ID                 3150 non-null   int64
 27  Survey Date                 3150 non-null   str
 28  Engagement Score            3150 non-null   int64
 29  Satisfaction Score          3150 non-null   int64
 30  Work-Life Balance Score     3150 non-null   int64
 31  Training Date               3150 non-null   str
 32  Training Program Name       3150 non-null   str
 33  Training Type               3150 non-null   str
 34  Training Outcome            3150 non-null   str
 35  Location                    3150 non-null   str
 36  Trainer                     3150 non-null   str
 37  Training Duration(Days)     3150 non-null   int64
 38  Training Cost               3150 non-null   float64
dtypes: float64(1), int64(8), str(30)
memory usage: 959.9 KB

In [35]:
## View basic statistics of the dataset
df.describe()

,Unnamed: 0,LocationCode,Current Employee Rating,Employee ID,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Duration(Days),Training Cost
count,3150.000000,3150.000000,3150.000000,3150.000000,3150.000000,3150.000000,3150.000000,3150.000000,3150.000000
mean,1495.748254,45155.332698,2.968254,2502.748254,2.943492,3.021270,2.992381,2.971746,560.525889
std,867.007861,30019.418852,1.020717,866.241991,1.430727,1.407413,1.409244,1.415390,262.485994
min,0.000000,1013.000000,1.000000,1001.000000,1.000000,1.000000,1.000000,1.000000,100.040000
25%,746.000000,17616.500000,2.000000,1750.250000,2.000000,2.000000,2.000000,2.000000,331.475000
50%,1495.500000,44455.500000,3.000000,2504.500000,3.000000,3.000000,3.000000,3.000000,574.300000
75%,2246.750000,71713.250000,3.000000,3254.750000,4.000000,4.000000,4.000000,4.000000,788.070000
max,2999.000000,98052.000000,5.000000,4000.000000,5.000000,5.000000,5.000000,5.000000,999.970000

In [36]:
## View the shape of the dataset
print(f"Total Records: {df.shape[0]} | Total Columns: {df.shape[1]}")

Total Records: 3150 | Total Columns: 39

Data Quality Checks

In [37]:
## Trim whitespace and clean text fields
text_cols = df.select_dtypes(include=['object', 'string']).columns
for col in text_cols:
    df[col] = df[col].astype(str).str.strip()

In [38]:
## Replace dirty strings wiht true null values
df.replace({"Unk": np.nan, "nan": np.nan, "": np.nan, "None": np.nan}, inplace=True)

,Unnamed: 0,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Satisfaction Score,Work-Life Balance Score,Training Date,Training Program Name,Training Type,Training Outcome,Location,Trainer,Training Duration(Days),Training Cost
0,0,Uriah,Bridges,20-Sep-19,NaN,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,...,2,3,15-Jul-23,Leadership Development,Internal,Failed,South Marisa,Taylor Rodriguez,2,606.11
1,1,Paula,Small,11-Feb-23,NaN,Production Technician I,Renee Mccormick,paula.small@bilearner.com,EW,Active,...,1,5,12-Sep-22,Customer Service,External,Incomplete,Tammieville,Kelly Patterson DDS,4,673.02
2,2,Edward,Buck,10-Dec-18,NaN,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,...,2,1,13-Aug-22,Leadership Development,External,Failed,East Roberthaven,Taylor Thomas,2,413.28
3,3,Michael,Riordan,21-Jun-21,NaN,Area Sales Manager,Rebekah Wright,michael.riordan@bilearner.com,CCDR,Active,...,5,4,15-Dec-22,Project Management,External,Completed,Garzatown,Holly Elliott,3,663.78
4,4,Jasmine,Onque,29-Jun-19,NaN,Area Sales Manager,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,...,5,3,13-Jul-23,Technical Skills,External,Failed,Lake Meganville,Donald Martinez,5,399.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3145,450,Oscar,Lopez,22-Oct-18,07-Apr-20,Network Engineer,Christian Ortega,oscar.lopez@bilearner.com,MSC,Active,...,3,4,04-Jun-23,Communication Skills,External,Passed,Markhaven,Jeremy Townsend,1,888.55
3146,2164,Cruz,Arellano,17-Sep-19,NaN,Area Sales Manager,Patricia Martinez,cruz.arellano@bilearner.com,SVG,Active,...,5,5,06-Oct-22,Customer Service,Internal,Completed,North Michaelbury,Jacob Johnson,2,745.31
3147,2372,Makenna,Foster,20-Apr-21,17-Sep-22,Production Technician I,Timothy Pratt,makenna.foster@bilearner.com,CCDR,Active,...,1,1,28-Jul-23,Communication Skills,Internal,Incomplete,Stephaniemouth,Debbie Arnold,1,543.46
3148,2012,Cordell,Vazquez,21-Aug-21,NaN,Production Manager,Paula Henderson,cordell.vazquez@bilearner.com,BPC,Active,...,3,5,29-Oct-22,Project Management,External,Failed,Port Joshuaborough,Shelby Fields,4,816.24
3149,270,Sonia,Skinner,28-Jun-20,NaN,Production Technician II,Connor Galloway,sonia.skinner@bilearner.com,PYZ,Active,...,4,1,24-Apr-23,Technical Skills,Internal,Failed,East Vincent,Jennifer Lopez,2,982.33

In [54]:
## Handle dates
date_cols = ['StartDate', 'ExitDate', 'DOB', 'Survey Date', 'Training Date']
for col in date_cols:
    df[col] = pd.to_datetime(df[col], dayfirst=True, format='mixed', errors='coerce').dt.strftime('%Y-%m-%d')

In [40]:
## Check for 100% duplicate rows
exact_duplicates = df.duplicated().sum()
print(f"100% Exact Row Duplicates: {exact_duplicates}")

## Check for duplicate Employee IDs
id_duplicates = df.duplicated(subset=['Employee ID']).sum()
print(f"Duplicate Employee IDs: {id_duplicates}")

100% Exact Row Duplicates: 150
Duplicate Employee IDs: 150

In [41]:
## Drop exact duplicate rows
df.drop_duplicates(inplace=True)

## Re-run the verification check
print(f"Remaining duplicate rows: {df.duplicated().sum()}")
print(f"Remaining duplicate IDs: {df.duplicated(subset=['Employee ID']).sum()}")

Remaining duplicate rows: 0
Remaining duplicate IDs: 0

In [42]:
## Remove unnamed column 
if 'Unnamed: 0' in df.columns:
    df.drop(columns=['Unnamed: 0'], inplace=True)

Feature Engineering

In [43]:
## Categorize if emplyees are active or terminated/exited
df['Is_Turnover'] = np.where(df['ExitDate'].notna(), 1, 0)
df['Is_Active'] = np.where(df['ExitDate'].isna(), 1, 0)
print(f"Feature Added: Terminated=1, Active=0")

Feature Added: Terminated=1, Active=0

In [44]:
## Calculate Tenure
today = pd.to_datetime('today')
df['Tenure_Years'] = np.where(
    df['ExitDate'].isna(),
    (today - df['StartDate']).dt.days /365,
    (df['ExitDate'] - df['StartDate']).dt.days/365
).round(2)
print(f"Feature Added: Calculate tenure up to today if active, and based on ExitDate if exited")

Feature Added: Calculate tenure up to today if active, and based on ExitDate if exited

In [45]:
## Create Tenure Buckets
def get_tenure_buckets(years):
    if years < 1: return "< 1 Year"
    elif 1 <= years < 3: return "1-3 Years"
    elif 3 <= years < 5: return "3-5 Years"
    else: return "5+ Years"

df['Tenure_Bucket'] = df['Tenure_Years'].apply(get_tenure_buckets)
print(f"Feature Added: Tenure Buckets")

Feature Added: Tenure Buckets

In [46]:
## Age Calculation
df['Age'] = ((today - df['DOB']).dt.days /365).astype(float).round(1)

def get_age_group(age):
    if age < 25: return "Under 25"
    elif 25 <= age < 35: return "25-34"
    elif 35 <= age < 50: return "35-49"
    else: return "50+"

df['Age_Group'] = df['Age'].apply(get_age_group)
print(f"Feature Added: Age Groups")

Feature Added: Age Groups

Export

In [55]:
excel_filename = r"C:\Users\Edumo\Desktop\Clean_HR_Dataset.xlsx"

with pd.ExcelWriter(excel_filename, engine='xlsxwriter') as writer:
    df.to_excel(writer, sheet_name='Cleaned Data', index=False)

print(f"Data Export Complete: Cleaned dataset saved to {excel_filename}")

Data Export Complete: Cleaned dataset saved to C:\Users\Edumo\Desktop\Clean_HR_Dataset.xlsx